// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package internal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID             pgtype.UUID
	Title          string
	SanitizedTitle string
	CreatedAt      pgtype.Timestamp
	Deleted        bool
}

type Patron struct {
	ID        pgtype.UUID
	FullName  string
	CreatedAt pgtype.Timestamp
	Deleted   bool
}

type Transaction struct {
	ID                pgtype.UUID
	GameID            pgtype.UUID
	PatronID          pgtype.UUID
	CheckoutTimestamp pgtype.Timestamp
	CheckinTimestamp  pgtype.Timestamp
}

type VwGameStatus struct {
	GameID            pgtype.UUID
	GameTitle         string
	SanitizedTitle    string
	PatronID          pgtype.UUID
	PatronFullName    pgtype.Text
	TransactionID     pgtype.UUID
	CheckoutTimestamp pgtype.Timestamp
	CheckinTimestamp  pgtype.Timestamp
}

type VwLibraryGame struct {
	ID             pgtype.UUID
	Title          string
	SanitizedTitle string
	CreatedAt      pgtype.Timestamp
}

type VwLibraryPatron struct {
	ID        pgtype.UUID
	FullName  string
	CreatedAt pgtype.Timestamp
}
