// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseErrorCode.
const (
	CONFLICT           ErrorResponseErrorCode = "CONFLICT"
	INTERNALERROR      ErrorResponseErrorCode = "INTERNAL_ERROR"
	MALFORMEDREQUEST   ErrorResponseErrorCode = "MALFORMED_REQUEST"
	NOTFOUND           ErrorResponseErrorCode = "NOT_FOUND"
	SERVICEUNAVAILABLE ErrorResponseErrorCode = "SERVICE_UNAVAILABLE"
	VALIDATIONERROR    ErrorResponseErrorCode = "VALIDATION_ERROR"
)

// CheckOutRequest Request payload for making a check in/out transaction
type CheckOutRequest struct {
	// GameId Game ID
	GameId openapi_types.UUID `json:"gameId"`

	// PatronId Patron ID
	PatronId openapi_types.UUID `json:"patronId"`
}

// CreateGameRequest Request payload for creating a new game
type CreateGameRequest struct {
	// Title The name of the board game
	Title string `json:"title"`
}

// CreatePatronRequest Request payload for creating a new patron
type CreatePatronRequest struct {
	// Name The name of the patron
	Name string `json:"name"`
}

// ErrorDetail Details about specific errors
type ErrorDetail struct {
	// Field The input field that caused the error
	Field string `json:"field"`

	// Message Human-readable error message for this field
	Message string `json:"message"`
}

// ErrorResponse Response when errors occur
type ErrorResponse struct {
	Error struct {
		// Code Machine readable error code
		Code ErrorResponseErrorCode `json:"code"`

		// Details Array of specific field errors. Empty if no specific errors
		Details []ErrorDetail `json:"details"`

		// Message Human-readable error message
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode Machine readable error code
type ErrorResponseErrorCode string

// Game A game in the library
type Game struct {
	// GameId Game ID
	GameId openapi_types.UUID `json:"gameId"`

	// Title The name of the board game
	Title string `json:"title"`
}

// GameList List of games with check out info
type GameList struct {
	// Games Array of the game statuses
	Games []GameStatus `json:"games"`
}

// GameStatus Game with check out info
type GameStatus struct {
	// CheckedOutAt ISO 8601 timestamp when the game was checked out
	CheckedOutAt *time.Time `json:"checkedOutAt,omitempty"`

	// Game A game in the library
	Game Game `json:"game"`

	// Patron A library patron
	Patron *Patron `json:"patron,omitempty"`
}

// LibraryTransaction Request payload for making a check in/out transaction
type LibraryTransaction struct {
	// GameId Game ID
	GameId openapi_types.UUID `json:"gameId"`

	// Id Transaction ID
	Id openapi_types.UUID `json:"id"`

	// PatronId Patron ID
	PatronId openapi_types.UUID `json:"patronId"`

	// Timestamp ISO 8601 timestamp when the transaction occurred in UTC
	Timestamp time.Time `json:"timestamp"`
}

// Patron A library patron
type Patron struct {
	// Name The name of the patron
	Name string `json:"name"`

	// PatronId Patron ID
	PatronId openapi_types.UUID `json:"patronId"`
}

// PatronList List of patrons with check out info
type PatronList struct {
	// Games Array of patrons
	Games *[]Patron `json:"games,omitempty"`
}

// CheckInGameParams defines parameters for CheckInGame.
type CheckInGameParams struct {
	// TransactionId Transaction ID
	TransactionId string `form:"transactionId" json:"transactionId"`
}

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	// CheckedOut Filter games by check out status (optional)
	CheckedOut *bool `form:"checkedOut,omitempty" json:"checkedOut,omitempty"`

	// Title Filter games by title (optional)
	Title *string `form:"title,omitempty" json:"title,omitempty"`
}

// ListPatronsParams defines parameters for ListPatrons.
type ListPatronsParams struct {
	// Name Filter patrons by name (optional)
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// CheckOutGameJSONRequestBody defines body for CheckOutGame for application/json ContentType.
type CheckOutGameJSONRequestBody = CheckOutRequest

// AddGameJSONRequestBody defines body for AddGame for application/json ContentType.
type AddGameJSONRequestBody = CreateGameRequest

// UpdateGameJSONRequestBody defines body for UpdateGame for application/json ContentType.
type UpdateGameJSONRequestBody = CreateGameRequest

// AddPatronJSONRequestBody defines body for AddPatron for application/json ContentType.
type AddPatronJSONRequestBody = CreatePatronRequest

// UpdatePatronJSONRequestBody defines body for UpdatePatron for application/json ContentType.
type UpdatePatronJSONRequestBody = CreatePatronRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/health)
	GetApiV1Health(c *gin.Context)
	// Check in a game
	// (POST /api/v1/library/checkin)
	CheckInGame(c *gin.Context, params CheckInGameParams)
	// Check out a game
	// (POST /api/v1/library/checkout)
	CheckOutGame(c *gin.Context)
	// Add a game
	// (POST /api/v1/library/game)
	AddGame(c *gin.Context)
	// Soft delete a game
	// (DELETE /api/v1/library/game/{gameId})
	DeleteGame(c *gin.Context, gameId string)
	// Get a game
	// (GET /api/v1/library/game/{gameId})
	GetGame(c *gin.Context, gameId string)
	// Update an existing game
	// (PUT /api/v1/library/game/{gameId})
	UpdateGame(c *gin.Context, gameId string)
	// Get list of all games with check out status
	// (GET /api/v1/library/games)
	ListGames(c *gin.Context, params ListGamesParams)
	// Add a patron
	// (POST /api/v1/library/patron)
	AddPatron(c *gin.Context)
	// Soft delete a patron
	// (DELETE /api/v1/library/patron/{patronId})
	DeletePatron(c *gin.Context, patronId string)
	// Get a patron
	// (GET /api/v1/library/patron/{patronId})
	GetPatron(c *gin.Context, patronId string)
	// Update an existing patron
	// (PUT /api/v1/library/patron/{patronId})
	UpdatePatron(c *gin.Context, patronId string)
	// Get list of all patrons
	// (GET /api/v1/library/patrons)
	ListPatrons(c *gin.Context, params ListPatronsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiV1Health operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Health(c)
}

// CheckInGame operation middleware
func (siw *ServerInterfaceWrapper) CheckInGame(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckInGameParams

	// ------------- Required query parameter "transactionId" -------------

	if paramValue := c.Query("transactionId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument transactionId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "transactionId", c.Request.URL.Query(), &params.TransactionId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter transactionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckInGame(c, params)
}

// CheckOutGame operation middleware
func (siw *ServerInterfaceWrapper) CheckOutGame(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckOutGame(c)
}

// AddGame operation middleware
func (siw *ServerInterfaceWrapper) AddGame(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddGame(c)
}

// DeleteGame operation middleware
func (siw *ServerInterfaceWrapper) DeleteGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGame(c, gameId)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGame(c, gameId)
}

// UpdateGame operation middleware
func (siw *ServerInterfaceWrapper) UpdateGame(c *gin.Context) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", c.Param("gameId"), &gameId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gameId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGame(c, gameId)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "checkedOut" -------------

	err = runtime.BindQueryParameter("form", true, false, "checkedOut", c.Request.URL.Query(), &params.CheckedOut)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checkedOut: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "title" -------------

	err = runtime.BindQueryParameter("form", true, false, "title", c.Request.URL.Query(), &params.Title)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter title: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGames(c, params)
}

// AddPatron operation middleware
func (siw *ServerInterfaceWrapper) AddPatron(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddPatron(c)
}

// DeletePatron operation middleware
func (siw *ServerInterfaceWrapper) DeletePatron(c *gin.Context) {

	var err error

	// ------------- Path parameter "patronId" -------------
	var patronId string

	err = runtime.BindStyledParameterWithOptions("simple", "patronId", c.Param("patronId"), &patronId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter patronId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePatron(c, patronId)
}

// GetPatron operation middleware
func (siw *ServerInterfaceWrapper) GetPatron(c *gin.Context) {

	var err error

	// ------------- Path parameter "patronId" -------------
	var patronId string

	err = runtime.BindStyledParameterWithOptions("simple", "patronId", c.Param("patronId"), &patronId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter patronId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPatron(c, patronId)
}

// UpdatePatron operation middleware
func (siw *ServerInterfaceWrapper) UpdatePatron(c *gin.Context) {

	var err error

	// ------------- Path parameter "patronId" -------------
	var patronId string

	err = runtime.BindStyledParameterWithOptions("simple", "patronId", c.Param("patronId"), &patronId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter patronId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePatron(c, patronId)
}

// ListPatrons operation middleware
func (siw *ServerInterfaceWrapper) ListPatrons(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPatronsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPatrons(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/health", wrapper.GetApiV1Health)
	router.POST(options.BaseURL+"/api/v1/library/checkin", wrapper.CheckInGame)
	router.POST(options.BaseURL+"/api/v1/library/checkout", wrapper.CheckOutGame)
	router.POST(options.BaseURL+"/api/v1/library/game", wrapper.AddGame)
	router.DELETE(options.BaseURL+"/api/v1/library/game/:gameId", wrapper.DeleteGame)
	router.GET(options.BaseURL+"/api/v1/library/game/:gameId", wrapper.GetGame)
	router.PUT(options.BaseURL+"/api/v1/library/game/:gameId", wrapper.UpdateGame)
	router.GET(options.BaseURL+"/api/v1/library/games", wrapper.ListGames)
	router.POST(options.BaseURL+"/api/v1/library/patron", wrapper.AddPatron)
	router.DELETE(options.BaseURL+"/api/v1/library/patron/:patronId", wrapper.DeletePatron)
	router.GET(options.BaseURL+"/api/v1/library/patron/:patronId", wrapper.GetPatron)
	router.PUT(options.BaseURL+"/api/v1/library/patron/:patronId", wrapper.UpdatePatron)
	router.GET(options.BaseURL+"/api/v1/library/patrons", wrapper.ListPatrons)
}
