version: '3.8'
services:
  frontend:
    image: alexsieland/bg-library-frontend:${APP_VERSION:-latest}
    restart: always
    environment:
      - BACKEND_PORT
      - EXPOSE_SWAGGER_UI=true
      - API_URL=http://
      - NGINX_HOST=${APP_HOST:-localhost}
      - SERVICE_NAME=nginx
    networks:
      - bg-library_frontend_nw
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ./frontend/nginx.tmpl:/etc/nginx/conf.d/nginx.conf.template:ro
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.32.0
    restart: always
    environment:
      - SWAGGER_JSON=http://backend:${BACKEND_PORT:-8080}/swagger/api.yaml
      - URL=http://${APP_HOST:-localhost}:${FRONTEND_PORT:-8080}
    networks:
      - bg-library_frontend_nw
    depends_on:
      - backend
    ports:
      - "81:8080"
  backend:
    image: alexsieland/bg-library-backend:${APP_VERSION:-latest}
    restart: always
    environment:
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - GIN_MODE
      - CORS_ALLOWED_ORIGIN=*
    networks:
      - bg-library_backend_nw
      - bg-library_frontend_nw
    ports:
      - ${BACKEND_PORT:-8080}:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18.2
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - bg-library_backend_nw
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/18/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  bg-library_backend_nw: {
    driver: bridge
  }
  bg-library_frontend_nw: {
    driver: bridge
  }

volumes:
  backend-cache: {}
  db-data: {}