// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlayToWinEntryDeletionType string

const (
	PlayToWinEntryDeletionTypeFailedToClaim    PlayToWinEntryDeletionType = "failed_to_claim"
	PlayToWinEntryDeletionTypeFoulPlay         PlayToWinEntryDeletionType = "foul_play"
	PlayToWinEntryDeletionTypeDuplicateEntrant PlayToWinEntryDeletionType = "duplicate_entrant"
	PlayToWinEntryDeletionTypeOther            PlayToWinEntryDeletionType = "other"
)

func (e *PlayToWinEntryDeletionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayToWinEntryDeletionType(s)
	case string:
		*e = PlayToWinEntryDeletionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayToWinEntryDeletionType: %T", src)
	}
	return nil
}

type NullPlayToWinEntryDeletionType struct {
	PlayToWinEntryDeletionType PlayToWinEntryDeletionType
	Valid                      bool // Valid is true if PlayToWinEntryDeletionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayToWinEntryDeletionType) Scan(value interface{}) error {
	if value == nil {
		ns.PlayToWinEntryDeletionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayToWinEntryDeletionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayToWinEntryDeletionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayToWinEntryDeletionType), nil
}

type PlayToWinGameDeletionType string

const (
	PlayToWinGameDeletionTypeClaimed PlayToWinGameDeletionType = "claimed"
	PlayToWinGameDeletionTypeMistake PlayToWinGameDeletionType = "mistake"
	PlayToWinGameDeletionTypeOther   PlayToWinGameDeletionType = "other"
)

func (e *PlayToWinGameDeletionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayToWinGameDeletionType(s)
	case string:
		*e = PlayToWinGameDeletionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayToWinGameDeletionType: %T", src)
	}
	return nil
}

type NullPlayToWinGameDeletionType struct {
	PlayToWinGameDeletionType PlayToWinGameDeletionType
	Valid                     bool // Valid is true if PlayToWinGameDeletionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayToWinGameDeletionType) Scan(value interface{}) error {
	if value == nil {
		ns.PlayToWinGameDeletionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayToWinGameDeletionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayToWinGameDeletionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayToWinGameDeletionType), nil
}

type PlayToWinSessionDeletionType string

const (
	PlayToWinSessionDeletionTypeFoulPlay         PlayToWinSessionDeletionType = "foul_play"
	PlayToWinSessionDeletionTypeTooManyPlayers   PlayToWinSessionDeletionType = "too_many_players"
	PlayToWinSessionDeletionTypeTooFewPlayers    PlayToWinSessionDeletionType = "too_few_players"
	PlayToWinSessionDeletionTypeAbnormalPlaytime PlayToWinSessionDeletionType = "abnormal_playtime"
	PlayToWinSessionDeletionTypeOther            PlayToWinSessionDeletionType = "other"
)

func (e *PlayToWinSessionDeletionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayToWinSessionDeletionType(s)
	case string:
		*e = PlayToWinSessionDeletionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayToWinSessionDeletionType: %T", src)
	}
	return nil
}

type NullPlayToWinSessionDeletionType struct {
	PlayToWinSessionDeletionType PlayToWinSessionDeletionType
	Valid                        bool // Valid is true if PlayToWinSessionDeletionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayToWinSessionDeletionType) Scan(value interface{}) error {
	if value == nil {
		ns.PlayToWinSessionDeletionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayToWinSessionDeletionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayToWinSessionDeletionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayToWinSessionDeletionType), nil
}

type TransactionEventType string

const (
	TransactionEventTypeCheckOut TransactionEventType = "check_out"
	TransactionEventTypeCheckIn  TransactionEventType = "check_in"
)

func (e *TransactionEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionEventType(s)
	case string:
		*e = TransactionEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionEventType: %T", src)
	}
	return nil
}

type NullTransactionEventType struct {
	TransactionEventType TransactionEventType
	Valid                bool // Valid is true if TransactionEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionEventType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionEventType), nil
}

type Game struct {
	ID             pgtype.UUID
	Title          string
	SanitizedTitle string
	CreatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	Barcode        pgtype.Text
}

type Patron struct {
	ID        pgtype.UUID
	FullName  string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	Barcode   pgtype.Text
}

type PlayToWinEntry struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	PlayToWinID           pgtype.UUID
	EntrantName           string
	EntrantUniqueID       string
	CreatedAt             pgtype.Timestamp
	DeletedAt             pgtype.Timestamp
	DeletionReason        NullPlayToWinEntryDeletionType
	DeletionReasonComment pgtype.Text
}

type PlayToWinGame struct {
	ID                    pgtype.UUID
	GameID                pgtype.UUID
	WinnerID              pgtype.UUID
	CreatedAt             pgtype.Timestamp
	DeletedAt             pgtype.Timestamp
	DeletionReason        NullPlayToWinGameDeletionType
	DeletionReasonComment pgtype.Text
}

type PlayToWinSession struct {
	ID                    pgtype.UUID
	PlayToWinID           pgtype.UUID
	PlaytimeMinutes       pgtype.Int4
	CreatedAt             pgtype.Timestamp
	DeletedAt             pgtype.Timestamp
	DeletionReason        NullPlayToWinSessionDeletionType
	DeletionReasonComment pgtype.Text
}

type Transaction struct {
	ID                pgtype.UUID
	GameID            pgtype.UUID
	PatronID          pgtype.UUID
	CheckoutTimestamp pgtype.Timestamp
	CheckinTimestamp  pgtype.Timestamp
}

type TransactionEvent struct {
	ID             pgtype.UUID
	TransactionID  pgtype.UUID
	GameID         pgtype.UUID
	PatronID       pgtype.UUID
	EventType      TransactionEventType
	EventTimestamp pgtype.Timestamp
	RecordedAt     pgtype.Timestamp
}

type VwDeletedPlayToWinEntry struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	DeletedAt             pgtype.Timestamp
	DeletionReason        NullPlayToWinEntryDeletionType
	DeletionReasonComment pgtype.Text
}

type VwDeletedPlayToWinGame struct {
	ID                    pgtype.UUID
	GameID                pgtype.UUID
	DeletedAt             pgtype.Timestamp
	DeletionReason        NullPlayToWinGameDeletionType
	DeletionReasonComment pgtype.Text
}

type VwDeletedPlayToWinSession struct {
	ID                    pgtype.UUID
	PlayToWinID           pgtype.UUID
	DeletedAt             pgtype.Timestamp
	DeletionReason        NullPlayToWinSessionDeletionType
	DeletionReasonComment pgtype.Text
}

type VwGameStatus struct {
	GameID            pgtype.UUID
	GameTitle         string
	SanitizedTitle    string
	PatronID          pgtype.UUID
	PatronFullName    pgtype.Text
	TransactionID     pgtype.UUID
	CheckoutTimestamp pgtype.Timestamp
	CheckinTimestamp  pgtype.Timestamp
	PlayToWinGameID   pgtype.UUID
}

type VwLibraryGame struct {
	ID              pgtype.UUID
	Title           string
	SanitizedTitle  string
	Barcode         pgtype.Text
	PlayToWinGameID pgtype.UUID
	CreatedAt       pgtype.Timestamp
}

type VwLibraryPatron struct {
	ID        pgtype.UUID
	FullName  string
	Barcode   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type VwLibraryTransactionEvent struct {
	TransactionID   pgtype.UUID
	GameID          pgtype.UUID
	GameTitle       string
	SanitizedTitle  pgtype.Text
	PatronID        pgtype.UUID
	PatronFullName  string
	EventTimestamp  pgtype.Timestamp
	EventType       TransactionEventType
	PlayToWinGameID pgtype.UUID
}

type VwPlayToWinEntry struct {
	ID              pgtype.UUID
	SessionID       pgtype.UUID
	PlayToWinID     pgtype.UUID
	EntrantName     string
	EntrantUniqueID string
	CreatedAt       pgtype.Timestamp
}

type VwPlayToWinEntryEvent struct {
	EntryID            pgtype.UUID
	SessionID          pgtype.UUID
	PlayToWinID        pgtype.UUID
	EntrantName        string
	EntrantUniqueID    string
	DeletionReason     NullPlayToWinEntryDeletionType
	PlaytimeMinutes    pgtype.Int4
	GameDeletionReason NullPlayToWinGameDeletionType
	GameTitle          pgtype.Text
	CreatedAt          pgtype.Timestamp
}

type VwPlayToWinGame struct {
	ID        pgtype.UUID
	GameID    pgtype.UUID
	CreatedAt pgtype.Timestamp
	WinnerID  pgtype.UUID
}

type VwPlayToWinGameOverview struct {
	PlayToWinID    pgtype.UUID
	GameID         pgtype.UUID
	GameTitle      string
	SanitizedTitle string
	CreatedAt      pgtype.Timestamp
	WinnerID       pgtype.UUID
	WinnerName     pgtype.Text
	WinnerUniqueID pgtype.Text
}

type VwPlayToWinSession struct {
	ID              pgtype.UUID
	PlayToWinID     pgtype.UUID
	PlaytimeMinutes pgtype.Int4
	CreatedAt       pgtype.Timestamp
}
