// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInGame = `-- name: CheckInGame :exec
UPDATE transactions
SET checkin_timestamp = now()
WHERE id = $1 AND checkin_timestamp IS NULL
`

func (q *Queries) CheckInGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, checkInGame, id)
	return err
}

const checkOutGame = `-- name: CheckOutGame :one
INSERT INTO transactions (game_id, patron_id) VALUES ($1, $2)
RETURNING id, game_id, patron_id, checkout_timestamp, checkin_timestamp
`

type CheckOutGameParams struct {
	GameID   pgtype.UUID
	PatronID pgtype.UUID
}

func (q *Queries) CheckOutGame(ctx context.Context, arg CheckOutGameParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, checkOutGame, arg.GameID, arg.PatronID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PatronID,
		&i.CheckoutTimestamp,
		&i.CheckinTimestamp,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games ( title, sanitized_title, barcode ) VALUES ( $1, $2, $3 )
RETURNING id, title, sanitized_title, created_at, deleted_at, barcode
`

type CreateGameParams struct {
	Title          string
	SanitizedTitle string
	Barcode        pgtype.Text
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.Title, arg.SanitizedTitle, arg.Barcode)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SanitizedTitle,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Barcode,
	)
	return i, err
}

const createPatron = `-- name: CreatePatron :one
INSERT INTO patrons ( full_name, barcode ) VALUES ( $1, $2 )
RETURNING id, full_name, created_at, deleted_at, barcode
`

type CreatePatronParams struct {
	FullName string
	Barcode  pgtype.Text
}

func (q *Queries) CreatePatron(ctx context.Context, arg CreatePatronParams) (Patron, error) {
	row := q.db.QueryRow(ctx, createPatron, arg.FullName, arg.Barcode)
	var i Patron
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Barcode,
	)
	return i, err
}

const createPlayToWinEntry = `-- name: CreatePlayToWinEntry :one
INSERT INTO play_to_win_entries (session_id, entrant_name, entrant_unique_id) VALUES ($1, $2, $3)
RETURNING id, session_id, entrant_name, entrant_unique_id, created_at, deleted_at, deletion_reason, deletion_reason_comment
`

type CreatePlayToWinEntryParams struct {
	SessionID       pgtype.UUID
	EntrantName     string
	EntrantUniqueID string
}

func (q *Queries) CreatePlayToWinEntry(ctx context.Context, arg CreatePlayToWinEntryParams) (PlayToWinEntry, error) {
	row := q.db.QueryRow(ctx, createPlayToWinEntry, arg.SessionID, arg.EntrantName, arg.EntrantUniqueID)
	var i PlayToWinEntry
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EntrantName,
		&i.EntrantUniqueID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.DeletionReasonComment,
	)
	return i, err
}

const createPlayToWinGame = `-- name: CreatePlayToWinGame :one
INSERT INTO play_to_win_games (game_id) VALUES ($1)
RETURNING id, game_id, created_at, deleted_at, deletion_reason, deletion_reason_comment
`

func (q *Queries) CreatePlayToWinGame(ctx context.Context, gameID pgtype.UUID) (PlayToWinGame, error) {
	row := q.db.QueryRow(ctx, createPlayToWinGame, gameID)
	var i PlayToWinGame
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.DeletionReasonComment,
	)
	return i, err
}

const createPlayToWinSession = `-- name: CreatePlayToWinSession :one
INSERT INTO play_to_win_sessions (play_to_win_id, playtime_minutes) VALUES ($1, $2)
RETURNING id, play_to_win_id, playtime_minutes, created_at, deleted_at, deletion_reason, deletion_reason_comment
`

type CreatePlayToWinSessionParams struct {
	PlayToWinID     pgtype.UUID
	PlaytimeMinutes pgtype.Int4
}

func (q *Queries) CreatePlayToWinSession(ctx context.Context, arg CreatePlayToWinSessionParams) (PlayToWinSession, error) {
	row := q.db.QueryRow(ctx, createPlayToWinSession, arg.PlayToWinID, arg.PlaytimeMinutes)
	var i PlayToWinSession
	err := row.Scan(
		&i.ID,
		&i.PlayToWinID,
		&i.PlaytimeMinutes,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.DeletionReasonComment,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
UPDATE games
    SET deleted_at = now()
WHERE deleted_at IS NULL AND id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const deletePatron = `-- name: DeletePatron :exec
UPDATE patrons
set deleted_at = now()
WHERE deleted_at IS NULL AND id = $1
`

func (q *Queries) DeletePatron(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePatron, id)
	return err
}

const deletePlayToWinEntry = `-- name: DeletePlayToWinEntry :exec
UPDATE play_to_win_entries
SET deleted_at = now(),
    deletion_reason = $2,
    deletion_reason_comment = $3
WHERE deleted_at IS NULL AND id = $1
`

type DeletePlayToWinEntryParams struct {
	ID                    pgtype.UUID
	DeletionReason        NullPlayToWinEntryDeletionType
	DeletionReasonComment pgtype.Text
}

func (q *Queries) DeletePlayToWinEntry(ctx context.Context, arg DeletePlayToWinEntryParams) error {
	_, err := q.db.Exec(ctx, deletePlayToWinEntry, arg.ID, arg.DeletionReason, arg.DeletionReasonComment)
	return err
}

const deletePlayToWinGame = `-- name: DeletePlayToWinGame :exec
UPDATE play_to_win_games
SET deleted_at = now(),
    deletion_reason = $2,
    deletion_reason_comment = $3
WHERE deleted_at IS NULL AND game_id = $1
`

type DeletePlayToWinGameParams struct {
	GameID                pgtype.UUID
	DeletionReason        NullPlayToWinGameDeletionType
	DeletionReasonComment pgtype.Text
}

func (q *Queries) DeletePlayToWinGame(ctx context.Context, arg DeletePlayToWinGameParams) error {
	_, err := q.db.Exec(ctx, deletePlayToWinGame, arg.GameID, arg.DeletionReason, arg.DeletionReasonComment)
	return err
}

const deletePlayToWinSession = `-- name: DeletePlayToWinSession :exec
UPDATE play_to_win_sessions
SET deleted_at = now(),
    deletion_reason = $2,
    deletion_reason_comment = $3
WHERE deleted_at IS NULL AND id = $1
`

type DeletePlayToWinSessionParams struct {
	ID                    pgtype.UUID
	DeletionReason        NullPlayToWinSessionDeletionType
	DeletionReasonComment pgtype.Text
}

func (q *Queries) DeletePlayToWinSession(ctx context.Context, arg DeletePlayToWinSessionParams) error {
	_, err := q.db.Exec(ctx, deletePlayToWinSession, arg.ID, arg.DeletionReason, arg.DeletionReasonComment)
	return err
}

const editGame = `-- name: EditGame :exec
UPDATE games
    SET title = $2,
        sanitized_title = $3,
        barcode = $4
WHERE id = $1
`

type EditGameParams struct {
	ID             pgtype.UUID
	Title          string
	SanitizedTitle string
	Barcode        pgtype.Text
}

func (q *Queries) EditGame(ctx context.Context, arg EditGameParams) error {
	_, err := q.db.Exec(ctx, editGame,
		arg.ID,
		arg.Title,
		arg.SanitizedTitle,
		arg.Barcode,
	)
	return err
}

const editPatron = `-- name: EditPatron :exec
UPDATE patrons
set full_name = $2,
    barcode = $3
WHERE id = $1
`

type EditPatronParams struct {
	ID       pgtype.UUID
	FullName string
	Barcode  pgtype.Text
}

func (q *Queries) EditPatron(ctx context.Context, arg EditPatronParams) error {
	_, err := q.db.Exec(ctx, editPatron, arg.ID, arg.FullName, arg.Barcode)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, title, sanitized_title, barcode, play_to_win_game_id, created_at
FROM vw_library_games
WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (VwLibraryGame, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i VwLibraryGame
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SanitizedTitle,
		&i.Barcode,
		&i.PlayToWinGameID,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByBarcode = `-- name: GetGameByBarcode :many
SELECT id, title, sanitized_title, barcode, play_to_win_game_id, created_at
FROM vw_library_games
WHERE barcode = $1
`

func (q *Queries) GetGameByBarcode(ctx context.Context, barcode pgtype.Text) ([]VwLibraryGame, error) {
	rows, err := q.db.Query(ctx, getGameByBarcode, barcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwLibraryGame
	for rows.Next() {
		var i VwLibraryGame
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SanitizedTitle,
			&i.Barcode,
			&i.PlayToWinGameID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameStatus = `-- name: GetGameStatus :one
SELECT game_id, game_title, sanitized_title, patron_id, patron_full_name, transaction_id, checkout_timestamp, checkin_timestamp, play_to_win_game_id
FROM vw_game_status
WHERE game_id = $1
`

func (q *Queries) GetGameStatus(ctx context.Context, gameID pgtype.UUID) (VwGameStatus, error) {
	row := q.db.QueryRow(ctx, getGameStatus, gameID)
	var i VwGameStatus
	err := row.Scan(
		&i.GameID,
		&i.GameTitle,
		&i.SanitizedTitle,
		&i.PatronID,
		&i.PatronFullName,
		&i.TransactionID,
		&i.CheckoutTimestamp,
		&i.CheckinTimestamp,
		&i.PlayToWinGameID,
	)
	return i, err
}

const getPatron = `-- name: GetPatron :one
SELECT id, full_name, barcode, created_at
FROM vw_library_patrons
WHERE id = $1
`

func (q *Queries) GetPatron(ctx context.Context, id pgtype.UUID) (VwLibraryPatron, error) {
	row := q.db.QueryRow(ctx, getPatron, id)
	var i VwLibraryPatron
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Barcode,
		&i.CreatedAt,
	)
	return i, err
}

const getPatronByBarcode = `-- name: GetPatronByBarcode :one
SELECT id, full_name, barcode, created_at
FROM vw_library_patrons
WHERE barcode = $1
`

func (q *Queries) GetPatronByBarcode(ctx context.Context, barcode pgtype.Text) (VwLibraryPatron, error) {
	row := q.db.QueryRow(ctx, getPatronByBarcode, barcode)
	var i VwLibraryPatron
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Barcode,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayToWinEntries = `-- name: GetPlayToWinEntries :many
SELECT
    id AS entry_id,
    session_id,
    play_to_win_id,
    entrant_name,
    entrant_unique_id,
    created_at
FROM vw_play_to_win_entries
WHERE play_to_win_id = $1
`

type GetPlayToWinEntriesRow struct {
	EntryID         pgtype.UUID
	SessionID       pgtype.UUID
	PlayToWinID     pgtype.UUID
	EntrantName     string
	EntrantUniqueID string
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) GetPlayToWinEntries(ctx context.Context, playToWinID pgtype.UUID) ([]GetPlayToWinEntriesRow, error) {
	rows, err := q.db.Query(ctx, getPlayToWinEntries, playToWinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayToWinEntriesRow
	for rows.Next() {
		var i GetPlayToWinEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.SessionID,
			&i.PlayToWinID,
			&i.EntrantName,
			&i.EntrantUniqueID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayToWinGame = `-- name: GetPlayToWinGame :one
SELECT id, game_id, created_at FROM vw_play_to_win_games
WHERE id = $1
`

func (q *Queries) GetPlayToWinGame(ctx context.Context, id pgtype.UUID) (VwPlayToWinGame, error) {
	row := q.db.QueryRow(ctx, getPlayToWinGame, id)
	var i VwPlayToWinGame
	err := row.Scan(&i.ID, &i.GameID, &i.CreatedAt)
	return i, err
}

const getPlayToWinSessions = `-- name: GetPlayToWinSessions :many
SELECT
    id AS session_id,
    play_to_win_id,
    playtime_minutes,
    created_at
FROM vw_play_to_win_sessions
WHERE play_to_win_id = $1
`

type GetPlayToWinSessionsRow struct {
	SessionID       pgtype.UUID
	PlayToWinID     pgtype.UUID
	PlaytimeMinutes pgtype.Int4
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) GetPlayToWinSessions(ctx context.Context, playToWinID pgtype.UUID) ([]GetPlayToWinSessionsRow, error) {
	rows, err := q.db.Query(ctx, getPlayToWinSessions, playToWinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayToWinSessionsRow
	for rows.Next() {
		var i GetPlayToWinSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.PlayToWinID,
			&i.PlaytimeMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckedOutGames = `-- name: ListCheckedOutGames :many
SELECT game_id, game_title, sanitized_title, patron_id, patron_full_name, transaction_id, checkout_timestamp, checkin_timestamp, play_to_win_game_id
FROM vw_game_status
WHERE checkin_timestamp IS NULL AND checkout_timestamp IS NOT NULL
ORDER BY sanitized_title
LIMIT $1 OFFSET $2
`

type ListCheckedOutGamesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCheckedOutGames(ctx context.Context, arg ListCheckedOutGamesParams) ([]VwGameStatus, error) {
	rows, err := q.db.Query(ctx, listCheckedOutGames, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwGameStatus
	for rows.Next() {
		var i VwGameStatus
		if err := rows.Scan(
			&i.GameID,
			&i.GameTitle,
			&i.SanitizedTitle,
			&i.PatronID,
			&i.PatronFullName,
			&i.TransactionID,
			&i.CheckoutTimestamp,
			&i.CheckinTimestamp,
			&i.PlayToWinGameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id, title, sanitized_title, barcode, play_to_win_game_id, created_at
FROM vw_library_games
ORDER BY sanitized_title
LIMIT $1 OFFSET $2
`

type ListGamesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListGames(ctx context.Context, arg ListGamesParams) ([]VwLibraryGame, error) {
	rows, err := q.db.Query(ctx, listGames, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwLibraryGame
	for rows.Next() {
		var i VwLibraryGame
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SanitizedTitle,
			&i.Barcode,
			&i.PlayToWinGameID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesStatus = `-- name: ListGamesStatus :many
SELECT game_id, game_title, sanitized_title, patron_id, patron_full_name, transaction_id, checkout_timestamp, checkin_timestamp, play_to_win_game_id
FROM vw_game_status
ORDER BY sanitized_title
LIMIT $1 OFFSET $2
`

type ListGamesStatusParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListGamesStatus(ctx context.Context, arg ListGamesStatusParams) ([]VwGameStatus, error) {
	rows, err := q.db.Query(ctx, listGamesStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwGameStatus
	for rows.Next() {
		var i VwGameStatus
		if err := rows.Scan(
			&i.GameID,
			&i.GameTitle,
			&i.SanitizedTitle,
			&i.PatronID,
			&i.PatronFullName,
			&i.TransactionID,
			&i.CheckoutTimestamp,
			&i.CheckinTimestamp,
			&i.PlayToWinGameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatrons = `-- name: ListPatrons :many
SELECT id, full_name, barcode, created_at
FROM vw_library_patrons
ORDER BY full_name
LIMIT $1 OFFSET $2
`

type ListPatronsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPatrons(ctx context.Context, arg ListPatronsParams) ([]VwLibraryPatron, error) {
	rows, err := q.db.Query(ctx, listPatrons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwLibraryPatron
	for rows.Next() {
		var i VwLibraryPatron
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Barcode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayToWinGames = `-- name: ListPlayToWinGames :many
SELECT
    ptw.id AS play_to_win_id,
    ptw.game_id AS game_id,
    g.title AS game_title,
    g.sanitized_title AS santized_title,
    ptw.created_at AS created_at
FROM vw_play_to_win_games AS ptw
LEFT JOIN games AS g ON g.id = ptw.game_id
WHERE sanitized_title ILIKE $1
LIMIT $2 OFFSET $3
`

type ListPlayToWinGamesParams struct {
	SanitizedTitle string
	Limit          int32
	Offset         int32
}

type ListPlayToWinGamesRow struct {
	PlayToWinID   pgtype.UUID
	GameID        pgtype.UUID
	GameTitle     pgtype.Text
	SantizedTitle pgtype.Text
	CreatedAt     pgtype.Timestamp
}

func (q *Queries) ListPlayToWinGames(ctx context.Context, arg ListPlayToWinGamesParams) ([]ListPlayToWinGamesRow, error) {
	rows, err := q.db.Query(ctx, listPlayToWinGames, arg.SanitizedTitle, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayToWinGamesRow
	for rows.Next() {
		var i ListPlayToWinGamesRow
		if err := rows.Scan(
			&i.PlayToWinID,
			&i.GameID,
			&i.GameTitle,
			&i.SantizedTitle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePlayToWinEntry = `-- name: RestorePlayToWinEntry :exec
UPDATE play_to_win_entries
SET deleted_at = NULL,
    deletion_reason = NULL,
    deletion_reason_comment = NULL
WHERE id = $1
`

func (q *Queries) RestorePlayToWinEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePlayToWinEntry, id)
	return err
}

const restorePlayToWinGame = `-- name: RestorePlayToWinGame :exec
UPDATE play_to_win_games
SET deleted_at = NULL,
    deletion_reason = NULL,
    deletion_reason_comment = NULL
WHERE deleted_at IS NOT NULL AND id = $1
`

func (q *Queries) RestorePlayToWinGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePlayToWinGame, id)
	return err
}

const restorePlayToWinSession = `-- name: RestorePlayToWinSession :exec
UPDATE play_to_win_sessions
SET deleted_at = NULL,
    deletion_reason = NULL,
    deletion_reason_comment = NULL
WHERE deleted_at IS NOT NULL AND id = $1
`

func (q *Queries) RestorePlayToWinSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePlayToWinSession, id)
	return err
}

const searchCheckedOutGames = `-- name: SearchCheckedOutGames :many
SELECT game_id, game_title, sanitized_title, patron_id, patron_full_name, transaction_id, checkout_timestamp, checkin_timestamp, play_to_win_game_id
FROM vw_game_status
WHERE checkin_timestamp IS NULL AND vw_game_status.sanitized_title ILIKE $1
ORDER BY sanitized_title
LIMIT $2 OFFSET $3
`

type SearchCheckedOutGamesParams struct {
	SanitizedTitle string
	Limit          int32
	Offset         int32
}

func (q *Queries) SearchCheckedOutGames(ctx context.Context, arg SearchCheckedOutGamesParams) ([]VwGameStatus, error) {
	rows, err := q.db.Query(ctx, searchCheckedOutGames, arg.SanitizedTitle, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwGameStatus
	for rows.Next() {
		var i VwGameStatus
		if err := rows.Scan(
			&i.GameID,
			&i.GameTitle,
			&i.SanitizedTitle,
			&i.PatronID,
			&i.PatronFullName,
			&i.TransactionID,
			&i.CheckoutTimestamp,
			&i.CheckinTimestamp,
			&i.PlayToWinGameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGameStatus = `-- name: SearchGameStatus :many
SELECT game_id, game_title, sanitized_title, patron_id, patron_full_name, transaction_id, checkout_timestamp, checkin_timestamp, play_to_win_game_id
FROM vw_game_status
WHERE sanitized_title ILIKE $1
ORDER BY sanitized_title
LIMIT $2 OFFSET $3
`

type SearchGameStatusParams struct {
	SanitizedTitle string
	Limit          int32
	Offset         int32
}

func (q *Queries) SearchGameStatus(ctx context.Context, arg SearchGameStatusParams) ([]VwGameStatus, error) {
	rows, err := q.db.Query(ctx, searchGameStatus, arg.SanitizedTitle, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwGameStatus
	for rows.Next() {
		var i VwGameStatus
		if err := rows.Scan(
			&i.GameID,
			&i.GameTitle,
			&i.SanitizedTitle,
			&i.PatronID,
			&i.PatronFullName,
			&i.TransactionID,
			&i.CheckoutTimestamp,
			&i.CheckinTimestamp,
			&i.PlayToWinGameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGames = `-- name: SearchGames :many
SELECT id, title, sanitized_title, barcode, play_to_win_game_id, created_at
FROM vw_library_games
WHERE sanitized_title ILIKE $1
ORDER BY sanitized_title
LIMIT $2 OFFSET $3
`

type SearchGamesParams struct {
	SanitizedTitle string
	Limit          int32
	Offset         int32
}

func (q *Queries) SearchGames(ctx context.Context, arg SearchGamesParams) ([]VwLibraryGame, error) {
	rows, err := q.db.Query(ctx, searchGames, arg.SanitizedTitle, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwLibraryGame
	for rows.Next() {
		var i VwLibraryGame
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SanitizedTitle,
			&i.Barcode,
			&i.PlayToWinGameID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatrons = `-- name: SearchPatrons :many
SELECT id, full_name, barcode, created_at
FROM vw_library_patrons
WHERE full_name ILIKE $1
ORDER BY full_name
LIMIT $2 OFFSET $3
`

type SearchPatronsParams struct {
	FullName string
	Limit    int32
	Offset   int32
}

func (q *Queries) SearchPatrons(ctx context.Context, arg SearchPatronsParams) ([]VwLibraryPatron, error) {
	rows, err := q.db.Query(ctx, searchPatrons, arg.FullName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VwLibraryPatron
	for rows.Next() {
		var i VwLibraryPatron
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Barcode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactionEvents = `-- name: SearchTransactionEvents :many
SELECT transaction_id, game_id, game_title, patron_id, patron_full_name, event_type, event_timestamp, play_to_win_game_id
FROM vw_library_transaction_events
WHERE sanitized_title ILIKE $1 AND patron_full_name ILIKE $2
LIMIT $3 OFFSET $4
`

type SearchTransactionEventsParams struct {
	SanitizedTitle pgtype.Text
	PatronFullName string
	Limit          int32
	Offset         int32
}

type SearchTransactionEventsRow struct {
	TransactionID   pgtype.UUID
	GameID          pgtype.UUID
	GameTitle       string
	PatronID        pgtype.UUID
	PatronFullName  string
	EventType       TransactionEventType
	EventTimestamp  pgtype.Timestamp
	PlayToWinGameID pgtype.UUID
}

func (q *Queries) SearchTransactionEvents(ctx context.Context, arg SearchTransactionEventsParams) ([]SearchTransactionEventsRow, error) {
	rows, err := q.db.Query(ctx, searchTransactionEvents,
		arg.SanitizedTitle,
		arg.PatronFullName,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTransactionEventsRow
	for rows.Next() {
		var i SearchTransactionEventsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.GameID,
			&i.GameTitle,
			&i.PatronID,
			&i.PatronFullName,
			&i.EventType,
			&i.EventTimestamp,
			&i.PlayToWinGameID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
