name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true
        cache-dependency-path: backend/go.sum

    - name: Run Unit Tests
      working-directory: ./backend
      run: make test

    - name: Run Integration Tests
      working-directory: ./backend
      run: make test-integration
